import React, { useState } from "react";
import Navbar from "../components/Navbar";
import PatientForm from "../components/PatientForm";
import LoadingSpinner from "../components/LoadingSpinner";
import PredictionCard from "../components/PredictionCard";
import ExplanationCard from "../components/ExplanationCard";
import RecommendationCard from "../components/RecommendationCard";
import AIReport from "../components/AIReport";
import DownloadReport from "../components/DownloadReport";
import "./Home.css";

function Home() {
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);
    const [error, setError] = useState(null);

    const handlePredictionStart = () => {
        setLoading(true);
        setError(null);
    };

    const handlePredictionSuccess = (data) => {
        setLoading(false);
        setResult(data);
        setError(null);
        // Smooth scroll to results
        setTimeout(() => {
            const el = document.getElementById("results-section");
            if (el) el.scrollIntoView({ behavior: "smooth" });
        }, 100);
    };

    const handlePredictionError = (errorMessage) => {
        setLoading(false);
        setError(errorMessage);
    };

    return (
        <div className="home-container">
            <Navbar />

            <main className="main-content">
                <div className="content-wrapper">
                    {/* Patient Screening Form */}
                    <PatientForm
                        onPredictionStart={handlePredictionStart}
                        onPredictionSuccess={handlePredictionSuccess}
                        onPredictionError={handlePredictionError}
                        loading={loading}
                    />

                    {/* Loading State */}
                    {loading && <LoadingSpinner />}

                    {/* Error Banner */}
                    {error && (
                        <div className="error-card">
                            <span className="error-icon">⚠️</span>
                            <div>
                                <h4 className="error-title">Prediction Execution Failed</h4>
                                <p className="error-message">{error}</p>
                            </div>
                        </div>
                    )}

                    {/* Dynamic Results Display */}
                    {result && !loading && (
                        <div id="results-section" className="results-container">
                            <div className="results-header">
                                <h2>Clinical Decision Support Dashboard</h2>
                                <p>Comprehensive assessment generated by multi-agent machine learning and LLM pipeline</p>
                            </div>

                            <PredictionCard prediction={result.prediction} />
                            
                            <ExplanationCard explanation={result.explanation} />
                            
                            <RecommendationCard recommendation={result.recommendation} />
                            
                            <AIReport llmReport={result.llm_report} />
                            
                            <DownloadReport pdfPath={result.pdf_path} />
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
}

export default Home;
